name: RDP Connection
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        
    - name: Install Desktop Environment
      run: |
        sudo apt-get update
        # sudo apt install -y ubuntu-desktop xrdp
        sudo apt-get install -y xrdp
        # Set SSL certificate (required for newer versions)
        sudo adduser xrdp ssl-cert
        # Configure XRDP to use XFCE (if you're using XFCE)
        echo "xfce4-session" > ~/.xsession
        sudo systemctl enable xrdp
        # sudo systemctl start xrdp
        sudo systemctl restart xrdp
        # Check XRDP status
        sudo systemctl status xrdp
        # Check if port 3389 is listening
        sudo netstat -tuln | grep 3389
        
    - name: Setup RDP Password
      run: |
        # Set password for existing runner user
        echo "runner:${{ secrets.RDP_PASSWORD }}" | sudo chpasswd
        
    - name: Start Cloudflare Tunnel
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      run: |
        sudo cloudflared service install ${CLOUDFLARE_TOKEN}
        sudo systemctl start cloudflared
        
    - name: Keep Alive
      run: |
        # XRDP logs
        sudo tail -f /var/log/xrdp.log
        sudo tail -f /var/log/xrdp-sesman.log
        sleep 6h

# name: Ubuntu Remote Access

# on:
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Setup Ubuntu
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y xfce4 xfce4-goodies
#         sudo apt-get install -y tightvncserver
        
#         # Create VNC password (minimum 6 characters)
#         mkdir -p ~/.vnc
#         echo 'Pass123' | vncpasswd -f > ~/.vnc/passwd
#         chmod 600 ~/.vnc/passwd
        
#         # Start VNC server
#         vncserver :1 -geometry 1280x800 -depth 24

#     - name: Setup Cloudflare Tunnel
#       env:
#         CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
#       run: |
#         curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
#         sudo dpkg -i cloudflared.deb
#         sudo cloudflared service install ${CLOUDFLARE_TOKEN}
#         sleep 10

#     - name: Install noVNC
#       run: |
#         git clone https://github.com/novnc/noVNC.git
#         cd noVNC
#         # port 6080
#         ./utils/novnc_proxy --vnc localhost:5901
